server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://ep-bold-art-atnxpmjb-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_xWLeKM8bQSC4
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: 4zV3u7A1x8N2y5K3w9P6q0r4s8v3z6A1x8N2y5K3w9P6q0r4s8v3z6A1x8N2y5
  expiration: 86400000 # 24 hours in milliseconds
